### ISSUE TITLE
In the generated config.json, there are some elements that are not used.

### ISSUE THREAD

**Issue by tkmru** [DeNA/DeClang#13]
`gen_config` を使って生成した`config.json`内にClangからは使われていない要素があるのを見つけました。`gen_config`が生成した`config.json`は次の通りです。

```
{
    "build_seed": "hello, i am seed",
    "overall_obfuscation": 0,
    "enable_obfuscation": 1,
    "flatten": [
        {
            "name": ".*main.*",
            "seed": "f05bc40ec305d18ff05bc40ec305d18f",
            "split_level": 1,
            "search_type": ""
        }
    ]
}
```

この中で`build_seed`, `search_type`がClangからは使われていなさそうでした。
それぞれをコード内で検索したところ、gen_configのコード以外では使われてなさそうです。

- https://github.com/DeNA/DeClang/search?q=build_seed
- https://github.com/DeNA/DeClang/search?q=search_type

正しいconfig例を知りたいです。また、configで指定する各要素の解説をREADMEに書いてもらえると助かります。

**Comment by funa-tk** [comment]
ご連絡、ありがとうございます！
確かに bundle_seed、search_typeともに利用していなさそうなので、削除した方が良さそうです。
config例と、configパラメータ解説の件は、承知しました。

**Comment by funa-tk** [comment]
詳細に調査してみたところ、
- build_seedは、flattenのseedを生成する種として使われていましたので残しておきます。
- search_typeは、全く利用していないので削除しました (0781a83)

**Comment by funa-tk** [comment]
README.meにパラメータの説明を書きました (8a1c5f9) ので、一旦本issueはクローズします。

**Comment by tkmru** [comment]
ありがとうございます！`flatten[seed]`、`flatten[split_level]`、`enable_obfuscation`についても書いておいてもらえると助かります！
