### ISSUE TITLE
Maybe declang won't check config.json

### ISSUE THREAD

**Issue by tkmru** [DeNA/DeClang#14]
declangがconfig.jsonを見てくれないようなので、一度確認してもらえると助かります。ビルドが通るものの難読化が行われず、log.txtは空のままです。
バイナリは[Release-Mac-swift5.4-v1.1.1.zip](https://github.com/DeNA/DeClang/releases/download/swift5.4-v1.1.1/Release-Mac-swift5.4-v1.1.1.zip)のものを使っています。macOS上でC言語のコードをビルドして動作確認しています。
ビルドするたびに、`DECLANG_HOME/.DeClang/log.txt`が生成されるので、パスは通っていそうです。

config.jsonを次に示します。

```
$ cat config.json 
{
    "build_seed": "hello, i am seed",
    "enable_obfuscation": 1,
    "overall_obfuscation": 100,
    "flatten": [
        {
            "name": ".*main.*",
            "seed": "aaaaaaa",
            "split_level": 10
        }
    ]
}
```

ビルドに使ったコードを次に示します。

```
$ cat test.c 
# include <stdio.h>
# include <stdlib.h>

int main(int argc, char *argv[]) {
  int a = atoi(argv[1]); 
  int b = 2;
  int sum = a + b;
  printf("%d", sum);
  return 0;
}
```

ビルドに使ったコマンドを次に示します。SDKROOTを設定していないとリンク時にエラーが出ます。

```
$ export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
$ DECLANG_HOME="/Users/tkmru/code/declang_path/" ./clang test.c 
```

log.txtは生成されるものの常に空です。

**Comment by funa-tk** [comment]
ご連絡、ありがとうございます。
ちなみに "-O2" 等の最適化オプション付きでビルドするとどうなりますでしょうか？

**Comment by tkmru** [comment]
うおおお、`-O2`をつけると動くようになりました。なるほど、最適化オプションをつけないと難読化パスに処理が渡らないんですね！

**Comment by funa-tk** [comment]
はい。そうなんです。解決してよかったです！
クローズします！
