### ISSUE TITLE
最適化なしで難読化をかける方法はありますか

### ISSUE THREAD

**Issue by tkmru** [DeNA/DeClang#16]
最適化をかけると難読化対象内部で使用しているライブラリ内でエラーが出て対応大変なので、最適化をかけずに難読化できる方法があると助かります。

**Comment by funa-tk** [comment]
"-O2" オプションが無くても、難読化できるようにすれば良さそうですね。
難読化の有効無効を"-O2" オプションで判断するのではなく config.json で制御する。

**Comment by funa-tk** [comment]
ちなみに、最適化をかけるとエラーになるケースってどんなケースですか・・？

**Comment by tkmru** [comment]
Androidライブラリに対して使おうとしていて、おそらくAndroid NDK内でエラー出てるのかなというかんじです

**Comment by tkmru** [comment]
@funa-tk build.gradle内で最適化オプションを指定するところを間違えていたのと、他のオプションと競合していたのが原因だったみたいで使えるようになりました！というわけで対応いただかなくても大丈夫です:bow:

**Comment by funa-tk** [comment]
承知しました！よかったです。
とりあえず今回は、対応なしということでクローズしたいと思います。
