### ISSUE TITLE
Failing when Archiving

### ISSUE THREAD

**Issue by OverwatchHeir** [DeNA/DeClang#2]
Hi,

I am trying to archive the project in order to create an obfuscated IPA file.

**Environment**:

- Xcode 12.1
- CocoaPods
- Build Settings:
  - Excluded Architectures:  **arm64**
  - Build Active Architecture Only : **YES**

-  Test Project: [DVIA-v2](https://github.com/prateek147/DVIA-v2)

**Steps for DVIA-v2**
1. Create **Pods** project

    ```shell
    cd ~/DVIA-v2/DVIA-v2/
    pod init
    pod install
    ```
2. Open from now on the **DVIA-v2.xcworkspace**

**Steps for DeClang**
1. Download the pre-built binary from [Releases page](https://github.com/DeNA/DeClang/releases/download/iOS-v1.0.0/Release-Mac-iOS-v1.0.0.zip).
2. Decompress the zip file and copy the Release folder to **~/.DeClang**.
   
   ```shell
   mv Release-v1.0.0/ ~/.DeClang 
   ```
3. Setup DeClang for Xcode:
    ```shell
    bash ~/.DeClang/script/xcode_setup.sh -p ~/DVIA-v2/DVIA-v2/DVIA-v2.xcodeproj
 
 
**Steps for creating obfuscated IPA file**   
1. In Xcode:
   
   1. Select as Target **Any iOS Device (arm64)**
   2. Product > Archive

**Issues**

Transcript: 

```shell
ld: libLTO is not loaded for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
![Screenshot 2020-11-11 at 14 42 35](https://user-images.githubusercontent.com/40168089/98833029-d4662100-243d-11eb-82e5-6055c3bde7c0.png)

**Comment by nevermoe** [comment]
Hi, thank you for the detailed report!
DeClang does not support swift yet because it is based on official llvm-project (not apple's llvm fork).
It only support C/C++ (such as project generated by Unity) and probably obj-C.

**Comment by nevermoe** [comment]
@OverwatchHeir 
Hi, It has been a while since your report. But I'm happy to announce that DeClang now supports Swift totally! Please refer to this [https://github.com/DeNA/DeClang/releases/tag/swift5.4-v1.1.0](release).
