### ISSUE TITLE
swift toolchain can`t distribute to appstoreConnect

### ISSUE THREAD

**Issue by lijunW** [DeNA/DeClang#22]
Is there any solution

**Comment by nevermoe** [comment]
Hi, do you mean your apps built by declang swift toolchain cannot be distributed to apple store? The release of toolchain based on swift5.4 probably obsoleted for Xcode 13 or above. We are planning to release declang toolchain based on swift5.5. However if you are in a hurry, I suggest you build the toolchain yourself.

**Comment by lijunW** [comment]
期待您的最新发布，并且希望能够支持直接分发到苹果商店
