### ISSUE TITLE
Warning appears when the -v option is specified.

### ISSUE THREAD

**Issue by tkmru** [DeNA/DeClang#23]
-vオプションを指定すると、`warning: argument unused during compilation: '-D DECLANG' [-Wunused-command-line-argument]`が出ます

```
$ ./clang -v
clang version 11.1.0 (https://github.com/DeNA/DeClang ec211549de54a69d8a1b877b4dcdb16b81fb9d75)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Users/tkmru/.DeClang/compiler/bin/.
clang: warning: argument unused during compilation: '-D DECLANG' [-Wunused-command-line-argument]
```

**Comment by nevermoe** [comment]
ここで -D DECLANGを追加しています：https://github.com/DeNA/DeClang/blob/swift/release/5.5/clang/lib/Driver/Driver.cpp#L993　。
Warning なので特に気にする必要がないと思います。

**Comment by tkmru** [comment]
>Warning なので特に気にする必要がないと思います。

何らかのコードをビルドしたときに出るWariningであればそうかなと思いますが、バージョンを確認しただけでWarningが出るのはツールとしておかしいと思うので、余裕があれば直してもらえると助かります

**Comment by nevermoe** [comment]
ソースコードを更新しましたので、ビルドしてみていただければと思います。
