### ISSUE TITLE
Could not build module 'Foundation' error in Xcode14.0

### ISSUE THREAD

**Issue by Ccatttt** [DeNA/DeClang#29]
Xcode 13 では正常ですが、Xcode14 ではそうではありません。この問題を修正する方法を教えてください。

**Comment by nevermoe** [comment]
ただ今対応中です。しばらくお待ちください。お急ぎの場合apple社のllvm-projectをcloneし、ご自身で移植してください。

**Comment by funa-tk** [comment]
Xcode14で利用できるバージョンをリリースいたしましたので、ご利用ください。
