### ISSUE TITLE
Can someone provide a compiled release version for windows?

### ISSUE THREAD

**Issue by 0x3f97** [DeNA/DeClang#3]

**Comment by nevermoe** [comment]
This?
[https://github.com/DeNA/DeClang/releases/tag/Android-v1.0.0](https://github.com/DeNA/DeClang/releases/tag/Android-v1.0.0)

**Comment by 0x3f97** [comment]
> This?
> https://github.com/DeNA/DeClang/releases/tag/Android-v1.0.0

Wow Thanks
