### ISSUE TITLE
Apple's  m1 chipset  support?

### ISSUE THREAD

**Issue by Noiled** [DeNA/DeClang#36]

**Comment by funa-tk** [comment]
M1 support is currently under development. It will be available within a few months!

**Comment by tkmru** [comment]
@funa-tk I was able to build DeClang on an Apple Silicon Mac without any problems, is there something wrong?

**Comment by funa-tk** [comment]
Yes, I have also comfirmed the latest DeClang can be build and used on Apple Silicon. We will release M1 Mac build soon!

**Comment by funa-tk** [comment]
We published new release with apple silicon binary.
