### ISSUE TITLE
Bitcode-enabled IPA Obfuscation

### ISSUE THREAD

**Issue by febryanapps** [DeNA/DeClang#4]
Hi, since this DeClang works on LLVM-level, I think it's possible to work and obfuscate on the IPA (iOS app) that is bitcode-enabled, as bitcode is LLVM IR. So for those who already have an IPA file, it might be faster to work on IPA directly rather than building from Xcode.

Examples of protectors using this mechanism are iXGuard and DexProtector.

Any idea how this works?
Thanks.

**Comment by nevermoe** [comment]
Hi, it's a good idea to apply the obfuscation to bitcode directly. However this implementation is beyond the original purpose of this project so we don't have a concrete plan to implement this feature in the near future. Anyway as it's  a good idea, any improvement will be welcome!
