### ISSUE TITLE
Can support Swift @Publushed ,$xxx.sink { }.store(in:) ?

### ISSUE THREAD

**Issue by lijunW** [DeNA/DeClang#42]
"A very good tool."
Can support @available()?
Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:

Can support Swift 
```
@Published var xxx: String? 
$xxx.sink { }.store(in:) 
```

**Comment by funa-tk** [comment]
DeClang (version: swift5.10-v1.0.0) supports @available and @Published. I checked it on my Mac (Xcode 15.4) and it works. It may not work if the version of Xcode is low.

**Comment by lijunW** [comment]
could not support Swift `if #available(iOS 15, *)`
`    
  override func viewDidLoad() {
        super.viewDidLoad()
        if #available(iOS 15, *) {
            
        }
    }
`
and within swift package Alamofire(5.9.1) and  some other swift package 

DeClang (version: swift5.10-v1.0.0)
(Xcode 15.4)

error:
Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      Swift._stdlib_isOSVersionAtLeast_AEIC(Builtin.Word, Builtin.Word, Builtin.Word) -> Builtin.Int1 in ViewController.o
      Swift._stdlib_isOSVersionAtLeast_AEIC(Builtin.Word, Builtin.Word, Builtin.Word) -> Builtin.Int1 in Alamofire.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
