### ISSUE TITLE
Swift support for iOS

### ISSUE THREAD

**Issue by alexcohn** [DeNA/DeClang#6]
I believe that this is on your roadmap, but just in case, let me file a feature request: to have the swift obfuscator support iOS targets, too.

**Comment by nevermoe** [comment]
Do you mean this: [https://github.com/DeNA/DeClang/releases/tag/swift5.4-v1.1.0](https://github.com/DeNA/DeClang/releases/tag/swift5.4-v1.1.0) ?

**Comment by alexcohn** [comment]
Yes, this is Mac OS only, isn't it?

**Comment by nevermoe** [comment]
Duplicate of #5 .
Solved.

**Comment by alexcohn** [comment]
Looks like the swift compiler did work.

**Comment by alexcohn** [comment]
But what I am missing are the instructions to control swift obfuscation. Currently, I get unobfuscated binary for swift.
